all:
	mbed compile --target NUCLEO_F401RE --toolchain GCC_ARM --profile ../cadmium.json --flash
#	mbed compile --target NUCLEO_F401RE --toolchain GCC_ARM --profile ../cadmium2.json --flash
#	mbed compile --target NUCLEO_F103RB --toolchain GCC_ARM --profile ../cadmium.json
#	mbed compile --target NUCLEO_F103RB --toolchain GCC_ARM --profile ../cadmium.json --flash
#	mbed compile --target NUCLEO_F401RE --toolchain GCC_ARM --profile ../cadmium.json
#	mbed compile --target NUCLEO_F401RE --toolchain GCC_ARM --profile ../cadmium.json --stats-depth 100
#	mbed compile --target NUCLEO_F401RE --toolchain GCC_ARM --profile develop --profile ../cadmium.json
